### ISSUE TITLE
[RFC] `invalidateQueries` and other `react-query` `useContext()`-fns

### ISSUE THREAD

**Issue by KATT** [trpc/examples-v10-next-prisma-starter-sqlite#3]
Current running proposal from me:

### Option A) - Tuples

**Given a procedure like**

```ts
t.router({
  post: t.router({
    byId: t.procedure
     .input(z.object({ id: z.string }))
     .query(() => '...' )
})
```

**We can do:**

```ts
// invalidate the whole "post router"
utils.invalidateQueries(['post']);
// Invalidate all `post.byId`-queries
utils.invalidateQueries(['post', 'byId']);
// invalidate specific post
utils.invalidateQueries(['post', 'byId', { id: "1" });
```

### Option B) String literals

How it works today, no ability to invalidate a full router without importing react-query and do it in a "type-unsafe" manner

### 🥇  Option C) `Proxy`! Current winning proposal.

Idea by @sachinraja 

```ts
function MyComponent() {
  // a proxy-based context helper?
  const utils = proxy.useContext()

  return <button onClick={() => utils.post.byId.invalidate(/* optional input */) } />
}

```

**Comment by sachinraja** [comment]
I am very against tuples, string literals, and anything like them. I don't see a good reason to go back to an API without the benefits of our proxy API, like go to definition. So here's my idea:
```ts
// invalidate the whole "post router"
proxy.post.invalidate()
// Invalidate all `post.byId`-queries
proxy.post.byId.invalidate()
// invalidate specific post
proxy.post.byId.invalidate({ id: "1" })
```
but it might be annoying to have this for every util function so we could maybe do this:
```ts
utils.invalidateQueries(proxy.post)
utils.invalidateQueries(proxy.post.byId)
utils.invalidateQueries(proxy.post.byId, { id: "1" })
```
(I'm not sure if this is possible, runtime wise)

**Comment by KATT** [comment]
Thinking in code below.... your idea would be something like this right?:


```ts
function MyComponent() {
  // a proxy-based context helper?
  const utils = proxy.useContext()

  return <button onClick={() => utils.post.byId.invalidate(/* optional input */) } />
}

```

**Comment by sachinraja** [comment]
Correct, although having another proxy might slow down TS if you have a lot of procedures

**Comment by woahitsraj** [comment]
I agree with this syntax. It seems much more declarative to invalidate the query directly on the proxy rather than utils. It's where I would intuitively  look for it. Would it be possible to do something like:

```jsx
import { trpc } from '../utils/trpc';

function MyComponent() {
  return <button onClick={() => trpc.proxy.post.list.invalidate(/* optional input */) } />
}
```

or in the case of the example in the repo:

```jsx
  const addPost = trpc.proxy.post.add.useMutation({
    async onSuccess() {
      // refetches posts after a post is added
     trpc.proxy.post.list.invalidate(/* optional input */)
    },
  });
```

**Comment by sachinraja** [comment]
We have a lot of other util functions though @woahitsraj and I wouldn't want them to all show there on autocomplete (maybe it's fine?). See [here](https://github.com/trpc/trpc/blob/843463a53f54ca3a42f5c098cec82d4185a5674c/packages/react/src/internals/context.tsx#L55-L212) for a full list. Although it could make sense to include core/commonly used ones.

Another idea is to have a separate property for it:
```ts
trpc.proxy.post.list.useQuery(/* input */)

trpc.proxy.post.list.util.invalidate(/* optional input */)
trpc.proxy.post.list.util.prefetchQuery(/* input */)
trpc.proxy.post.list.util.setQueryData(/* optional input */, /* updater */)
```

**Comment by KATT** [comment]
Bare in mind we need to do a `const utils = proxy.useContext()` ahead of calling invalidation/prefetch/etc

**Comment by KATT** [comment]
Created: https://github.com/trpc/trpc/issues/2113
